import { createSlice } from '@reduxjs/toolkit';

const sectionsSlice = createSlice({
  name: 'sections',
  initialState: {
    arr: [
      'dashboard',
      'incidents',
      'clouds',
      'stacks',
      'clusters',
      'machines',
      'volumes',
      'buckets',
      'networks',
      'zones',
      'images',
      'keys',
      'scripts',
      'templates',
      'secrets',
      'tunnels',
      'schedules',
      'rules;',
      'teams',
    ],
    obj: {
      dashboard: {
        id: 'dashboard',
        icon: 'icons:dashboard',
        color: '#424242',
        sidebar: false,
        tile: false,
        hr: true,
      },
      incidents: {
        id: 'incidents',
        color: '#d96557',
        sidebar: false,
        tile: false,
      },
      clouds: {
        id: 'clouds',
        color: '#424242',
        icon: 'cloud',
        add: '/clouds/+add',
        sidebar: true,
        tile: false,
        hr: false,
      },
      stacks: {
        id: 'stacks',
        color: '#0277BD',
        icon: 'maps:layers',
        sidebar: true,
        tile: true,
        hr: true,
        hideZero: true,
        hideTileIfZero: true,
      },
      clusters: {
        id: 'clusters',
        color: '#aa646c',
        icon: 'icons:group-work',
        add: '',
        sidebar: true,
        tile: true,
        hideZero: true,
      },
      machines: {
        id: 'machines',
        color: '#8c76d1',
        icon: 'hardware:computer',
        add: '/machines/+create',
        sidebar: true,
        tile: true,
      },
      volumes: {
        id: 'volumes',
        color: '#795548',
        icon: 'device:storage',
        add: '/volumes/+add',
        sidebar: true,
        tile: true,
        hideTileIfZero: true,
      },
      buckets: {
        id: 'buckets',
        color: '#ff590b',
        icon: 'icons:folder',
        add: '/buckets/+add',
        sidebar: true,
        tile: true,
        hideZero: true,
      },
      networks: {
        id: 'networks',
        color: '#795548',
        icon: 'hardware:device-hub',
        add: '/networks/+add',
        sidebar: true,
        tile: true,
        hideTileIfZero: true,
      },
      zones: {
        id: 'zones',
        color: '#3F51B5',
        icon: 'icons:dns',
        add: '/zones/+add',
        sidebar: true,
        tile: true,
        hideTileIfZero: true,
      },
      images: {
        id: 'images',
        color: '#0099cc',
        icon: 'image:collections',
        sidebar: true,
        tile: true,
        q: '',
        hr: true,
      },
      keys: {
        id: 'keys',
        color: '#009688',
        icon: 'communication:vpn-key',
        add: '/keys/+add',
        sidebar: true,
        tile: false,
        hideTileIfZero: false,
      },
      scripts: {
        id: 'scripts',
        color: '#D48900',
        icon: 'icons:code',
        add: '/scripts/+add',
        sidebar: true,
        tile: true,
        hideTileIfZero: true,
      },
      templates: {
        id: 'templates',
        color: '#0097A7',
        icon: 'icons:extension',
        add: '/templates/+add',
        sidebar: true,
        tile: true,
        hr: true,
        hideTileIfZero: true,
      },
      secrets: {
        id: 'secrets',
        color: '#1D1C1A',
        icon: 'icons:lock',
        add: '/secrets/+add',
        sidebar: true,
        tile: true,
        hideZero: false,
        hideTileIfZero: true,
      },
      tunnels: {
        id: 'tunnels',
        color: '#795548',
        icon: 'editor:merge-type',
        add: '/tunnels/+add',
        sidebar: false,
        tile: false,
        hideTileIfZero: true,
      },
      schedules: {
        id: 'schedules',
        color: '#43A047',
        icon: 'event',
        add: '/schedules/+add',
        sidebar: true,
        tile: true,
      },
      rules: {
        id: 'rules',
        color: '#42424242',
        icon: 'vaadin:scale-unbalance',
        add: '/rules/+add',
        sidebar: true,
        tile: true,
      },
      teams: {
        id: 'teams',
        color: '#607D8B',
        icon: 'social:people',
        sidebar: true,
        tile: true,
        hr: true,
      },
      account: {
        id: 'account',
        color: '#2F2F3E',
        icon: 'account-circle',
        count: null,
      },
      members: {
        id: 'members',
        color: '#607D8B',
        icon: 'social:people',
      },
      insights: {
        id: 'insights',
        color: '#2F2F3E',
        icon: 'icons:trending-up',
        sidebar: true,
        tile: false,
      },
    },
  },
  reducers: {
    sectionsUpdated(state, action) {
      return {
        ...action.payload,
      };
    },
  },
});

export const { sectionsUpdated } = sectionsSlice.actions;
export default sectionsSlice.reducer;
